repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v1.5.0
    hooks:
      - id: clang-format
        args: [--style=file]
